x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  rootstock:
    restart: "unless-stopped"
    image: rsksmart/rskj:${ROOTSTOCK_DOCKER_TAG}
    platform: linux/amd64
    volumes:
      - rootstock-data:/var/lib/rsk
      - ./rootstock/override.conf:/var/lib/rsk/override.conf:ro
    ports:
      - ${P2P_PORT:-5050}:5050/tcp
      - ${P2P_PORT:-5050}:5050/udp
    environment:
      - RSKJ_SYS_PROPS=${RSKJ_SYS_PROPS}
      - RSKJ_LOG_PROPS=-Dlogging.stdout=${LOG_LEVEL}
    labels:
      - traefik.enable=true

      # rpc
      - traefik.http.routers.${RPC_HOST:-rootstock}.service=${RPC_HOST:-rootstock}
      - traefik.http.routers.${RPC_HOST:-rootstock}.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-rootstock}.rule=Host(`${RPC_HOST:-rootstock}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-rootstock}.tls.certresolver=letsencrypt
      - traefik.http.routers.${RPC_HOST:-rootstock}lb.service=${RPC_HOST:-rootstock}
      - traefik.http.routers.${RPC_HOST:-rootstock}lb.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-rootstock}lb.rule=Host(`${RPC_LB:-rootstock-lb}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-rootstock}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${RPC_HOST:-rootstock}.loadbalancer.server.port=4444

      # WS
      - traefik.http.routers.${WS_HOST:-rootstockws}.service=${WS_HOST:-rootstockws}
      - traefik.http.routers.${WS_HOST:-rootstockws}.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-rootstockws}.rule=Host(`${WS_HOST:-rootstockws}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-rootstockws}.tls.certresolver=letsencrypt
      - traefik.http.routers.${WS_HOST:-rootstockws}lb.service=${WS_HOST:-rootstockws}
      - traefik.http.routers.${WS_HOST:-rootstockws}lb.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-rootstockws}lb.rule=Host(`${WS_LB:-rootstockws-lb}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-rootstockws}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${WS_HOST:-rootstockws}.loadbalancer.server.port=4445
    <<: *logging

volumes:
  rootstock-data:
